name: FolderArt
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true
targets:
  FolderArt:
    type: application
    platform: macOS
    sources:
      - path: FolderArt
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.FolderArt
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        SWIFT_VERSION: 5.9
        ENABLE_HARDENED_RUNTIME: YES
        INFOPLIST_FILE: FolderArt/Info.plist
    entitlements:
      path: FolderArt/FolderArt.entitlements
    info:
      path: FolderArt/Info.plist
      properties:
        LSMinimumSystemVersion: "$(MACOSX_DEPLOYMENT_TARGET)"
        CFBundleName: FolderArt
        NSHumanReadableCopyright: "Copyright © 2026. All rights reserved."
  FolderArtTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: FolderArtTests
    dependencies:
      - target: FolderArt
    settings:
      base:
        SWIFT_VERSION: 5.9
